### PR TITLE
missing DIP_EXPORT for Pixel operator !=

### LINKED ISSUE #208: Missing DIP_EXPORT for Image::Pixel != Image::Pixel (image_views.h)
**Component**
DIPlib - branch: master - commit: f1db9f127416379b1ef9873249329e39cd298353

**Describe the bug**
Missing DIP_EXPORT for operator != in include/diplib/library/image_views.h at line 787

**To Reproduce**

```
#include <iostream>
#include <diplib.h>
#include <diplib/generation.h>

int main() {
    const dip::Image kernelImageA = dip::CreateGauss({1.0}, {3}, 3, {0});
    const dip::Image kernelImageB = dip::CreateGauss({3.0}, {3}, 3, {0});

    if ( !(kernelImageA.At(0) == kernelImageB.At(0)) ) {
        std::cout << "expected" << std::endl;
    }

    //doesn't compile missing DIP_EXPORT for Image::Pixel != Image::Pixel in include/diplib/library/image_views.h at line 787
    if ( kernelImageA.At(0) != kernelImageB.At(0) ) {
        std::cout << "also expected" << std::endl;
    }

    return 0;
}
```

**System information:**
 - Ubuntu 24.04
 - PyDIP: n/a
 - DIPimage: n/a
 - CMake: 4.0.2, cc 13.3.0, c++ 13.3.0

**Aditional notes:**
I'm going to submit a quick PR for this one

### PR DESCRIPTION
**Pull request by VisualFox**
attempt to fix #208

```
//doesn't compile missing DIP_EXPORT for Image::Pixel != Image::Pixel in include/diplib/library/image_views.h at line 787
if ( kernelImageA.At(0) != kernelImageB.At(0) ) {
    std::cout << "also expected" << std::endl;
}
```

### CODE REVIEW

File: include/diplib/library/image_views.h [hunk 1]
```diff
@@ -784,6 +784,7 @@ bool operator==( Image::Pixel const& lhs, T const& rhs ) { return operator==( lh
 
 /// \brief Comparison operator, equivalent to `!(lhs==rhs)`.
 /// \relates dip::Image::Pixel
+DIP_EXPORT bool operator!=( Image::Pixel const& lhs, Image::Pixel const& rhs );
```
Comment (crisluengo) [inline include/diplib/library/image_views.h:787]: A trivial function like this can be defined inline:
```cpp
inline bool operator!=( Image::Pixel const& lhs, Image::Pixel const& rhs ) { return !( lhs == rhs ); }
```

Comment (VisualFox) [reply include/diplib/library/image_views.h:787]: Can I just implement it in image_view.h in this case? Seem a bit silly to put that one in pixel.cpp

Comment (crisluengo) [reply include/diplib/library/image_views.h:787]: Yes, that was the intention. That allows the optimizing compiler to skip one function call.

Comment (VisualFox) [reply include/diplib/library/image_views.h]: done!
